version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda2s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eq8ej2shdznk"
s3_prefix = "lambda2s3"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "HTMLBucket=\"s3-lambda-kgoto\""

