AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda2s3

  Sample SAM Template for lambda2s3
  
# lambda関数の共通の設定
Globals:
  Function:
    Timeout: 3

# バケット名を起動時に設定したい
Parameters:
  HTMLBucket:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - AmazonS3FullAccess # s3へのアクセス権
      Environment: 
        Variables:
          BucketName: !Sub ${HTMLBucket} # lambda内で使いたい変数
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
